CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS compte (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pseudo VARCHAR(16) NOT NULL,
    legacy_pseudo VARCHAR(80),
    username_change_required BOOLEAN,
    mail VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email_verified BOOLEAN,
    email_confirmation_token VARCHAR(128),
    email_confirmation_expires_at TIMESTAMP WITH TIME ZONE,
    password_reset_token VARCHAR(128),
    password_reset_expires_at TIMESTAMP WITH TIME ZONE,
    display_name VARCHAR(80),
    profile_bio VARCHAR(500),
    profile_status VARCHAR(100),
    favorite_anime VARCHAR(160),
    accent_color VARCHAR(16),
    profil_picture BYTEA,
    profile_picture_content_type VARCHAR(80),
    background BYTEA,
    background_content_type VARCHAR(80),
    show_followers BOOLEAN,
    show_following BOOLEAN,
    show_anime_library BOOLEAN,
    show_manga_library BOOLEAN,
    last_active_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_compte_pseudo UNIQUE (pseudo),
    CONSTRAINT uk_compte_mail UNIQUE (mail)
);

CREATE TABLE IF NOT EXISTS anime_catalog_entry (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mal_id INTEGER NOT NULL,
    slug VARCHAR(140) NOT NULL,
    title VARCHAR(260) NOT NULL,
    title_english VARCHAR(260),
    title_japanese VARCHAR(260),
    image_url VARCHAR(700),
    background_url VARCHAR(700),
    synopsis VARCHAR(5000),
    type VARCHAR(40),
    episodes INTEGER,
    status VARCHAR(80),
    score DOUBLE PRECISION,
    anime_rank INTEGER,
    popularity INTEGER,
    season VARCHAR(32),
    anime_year INTEGER,
    genres VARCHAR(1200),
    studios VARCHAR(1200),
    trailer_url VARCHAR(700),
    last_synced_at TIMESTAMP WITH TIME ZONE NOT NULL,
    characters_synced_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_anime_catalog_mal_id UNIQUE (mal_id)
);

CREATE TABLE IF NOT EXISTS anime_weekly_ranking (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anime_mal_id INTEGER NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    rank_position INTEGER NOT NULL,
    weekly_score DOUBLE PRECISION NOT NULL,
    source VARCHAR(80) NOT NULL,
    captured_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_anime_weekly_ranking_period_source_anime UNIQUE (source, period_start, period_end, anime_mal_id),
    CONSTRAINT fk_anime_weekly_ranking_anime FOREIGN KEY (anime_mal_id) REFERENCES anime_catalog_entry(mal_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS character_catalog_entry (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mal_id INTEGER NOT NULL,
    slug VARCHAR(140) NOT NULL,
    name VARCHAR(260) NOT NULL,
    name_kanji VARCHAR(260),
    image_url VARCHAR(700),
    favorites INTEGER,
    about VARCHAR(12000),
    nicknames VARCHAR(1600),
    source_anime_mal_id INTEGER,
    source_anime_title VARCHAR(260),
    source_anime_slug VARCHAR(140),
    source_anime_image_url VARCHAR(700),
    role VARCHAR(40),
    last_synced_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_character_catalog_mal_id UNIQUE (mal_id)
);

CREATE TABLE IF NOT EXISTS account_follow (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id INTEGER NOT NULL REFERENCES compte(id),
    followed_id INTEGER NOT NULL REFERENCES compte(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_account_follow_pair UNIQUE (follower_id, followed_id)
);

CREATE TABLE IF NOT EXISTS anime_library_entry (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL REFERENCES compte(id),
    anime_slug VARCHAR(140) NOT NULL,
    parent_anime_slug VARCHAR(140),
    parent_title VARCHAR(180),
    season_slug VARCHAR(140),
    season_title VARCHAR(180),
    season_number INTEGER,
    tracking_mode VARCHAR(20),
    media_type VARCHAR(40),
    title VARCHAR(180) NOT NULL,
    cover_url VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    watched_episodes INTEGER NOT NULL,
    total_episodes INTEGER NOT NULL,
    score INTEGER,
    favorite BOOLEAN NOT NULL,
    notes VARCHAR(1200),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_anime_library_account_slug UNIQUE (account_id, anime_slug)
);

CREATE TABLE IF NOT EXISTS manga_library_entry (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL REFERENCES compte(id),
    manga_slug VARCHAR(140) NOT NULL,
    title VARCHAR(180) NOT NULL,
    cover_url VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    read_chapters INTEGER NOT NULL,
    total_chapters INTEGER NOT NULL,
    score INTEGER,
    favorite BOOLEAN NOT NULL,
    notes VARCHAR(1200),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_manga_library_account_slug UNIQUE (account_id, manga_slug)
);

CREATE TABLE IF NOT EXISTS feed_activity_like (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL REFERENCES compte(id) ON DELETE CASCADE,
    activity_owner_id INTEGER NOT NULL REFERENCES compte(id) ON DELETE CASCADE,
    activity_type VARCHAR(20) NOT NULL,
    activity_entry_id INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_feed_activity_like_account_activity UNIQUE (account_id, activity_type, activity_entry_id)
);

CREATE TABLE IF NOT EXISTS account_notification (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id INTEGER NOT NULL REFERENCES compte(id),
    actor_id INTEGER NOT NULL REFERENCES compte(id),
    type VARCHAR(32) NOT NULL,
    read_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS account_message (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id INTEGER NOT NULL REFERENCES compte(id),
    recipient_id INTEGER NOT NULL REFERENCES compte(id),
    content VARCHAR(1000) NOT NULL,
    image_data BYTEA,
    image_content_type VARCHAR(80),
    read_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS anime_character_appearance (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anime_mal_id INTEGER NOT NULL,
    anime_slug VARCHAR(140),
    anime_title VARCHAR(260),
    anime_image_url VARCHAR(700),
    character_mal_id INTEGER NOT NULL,
    role VARCHAR(40),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_anime_character_appearance UNIQUE (anime_mal_id, character_mal_id)
);

CREATE TABLE IF NOT EXISTS translation_cache_entry (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key VARCHAR(80) NOT NULL,
    source_language VARCHAR(8) NOT NULL,
    target_language VARCHAR(8) NOT NULL,
    source_text VARCHAR(5000) NOT NULL,
    translated_text VARCHAR(12000) NOT NULL,
    provider VARCHAR(40) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_used_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_translation_cache_key UNIQUE (cache_key)
);

CREATE INDEX IF NOT EXISTS idx_translation_cache_languages ON translation_cache_entry (source_language, target_language);

CREATE INDEX IF NOT EXISTS idx_compte_lower_pseudo ON compte (lower(pseudo));
CREATE INDEX IF NOT EXISTS idx_compte_lower_mail ON compte (lower(mail));
CREATE INDEX IF NOT EXISTS idx_compte_lower_legacy_pseudo ON compte (lower(legacy_pseudo));
CREATE INDEX IF NOT EXISTS idx_compte_email_confirmation_token ON compte (email_confirmation_token);
CREATE INDEX IF NOT EXISTS idx_compte_password_reset_token ON compte (password_reset_token);

CREATE INDEX IF NOT EXISTS idx_account_follow_followed_created ON account_follow (followed_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_account_follow_follower_created ON account_follow (follower_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_account_notification_recipient_created ON account_notification (recipient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_account_notification_recipient_unread ON account_notification (recipient_id, read_at);
CREATE INDEX IF NOT EXISTS idx_account_notification_recipient_type_unread ON account_notification (recipient_id, type, read_at);

CREATE INDEX IF NOT EXISTS idx_account_message_pair ON account_message (sender_id, recipient_id, created_at);
CREATE INDEX IF NOT EXISTS idx_account_message_reverse_pair ON account_message (recipient_id, sender_id, created_at);
CREATE INDEX IF NOT EXISTS idx_account_message_unread ON account_message (recipient_id, sender_id, read_at);

CREATE INDEX IF NOT EXISTS idx_anime_library_account_updated ON anime_library_entry (account_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_manga_library_account_updated ON manga_library_entry (account_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_feed_activity_like_activity ON feed_activity_like (activity_type, activity_entry_id);
CREATE INDEX IF NOT EXISTS idx_feed_activity_like_account ON feed_activity_like (account_id);
CREATE INDEX IF NOT EXISTS idx_feed_activity_like_owner ON feed_activity_like (activity_owner_id);

CREATE INDEX IF NOT EXISTS idx_anime_catalog_title ON anime_catalog_entry (title);
CREATE INDEX IF NOT EXISTS idx_anime_catalog_popularity ON anime_catalog_entry (popularity);
CREATE INDEX IF NOT EXISTS idx_anime_catalog_filters ON anime_catalog_entry (status, anime_year, season, score, type);
CREATE INDEX IF NOT EXISTS idx_anime_catalog_pending_character_sync
    ON anime_catalog_entry (popularity, title, mal_id)
    WHERE mal_id IS NOT NULL AND characters_synced_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_anime_weekly_ranking_latest ON anime_weekly_ranking (period_end, rank_position);
CREATE INDEX IF NOT EXISTS idx_anime_weekly_ranking_anime ON anime_weekly_ranking (anime_mal_id);
CREATE INDEX IF NOT EXISTS idx_anime_catalog_title_trgm ON anime_catalog_entry USING GIN (lower(title) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_anime_catalog_title_english_trgm ON anime_catalog_entry USING GIN (lower(title_english) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_anime_catalog_title_japanese_trgm ON anime_catalog_entry USING GIN (lower(title_japanese) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_anime_catalog_genres_trgm ON anime_catalog_entry USING GIN (lower(genres) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_anime_catalog_studios_trgm ON anime_catalog_entry USING GIN (lower(studios) gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_character_source_anime_mal_id ON character_catalog_entry (source_anime_mal_id);
CREATE INDEX IF NOT EXISTS idx_character_catalog_name ON character_catalog_entry (name);
CREATE INDEX IF NOT EXISTS idx_character_catalog_favorites ON character_catalog_entry (favorites DESC);
CREATE INDEX IF NOT EXISTS idx_character_catalog_name_trgm ON character_catalog_entry USING GIN (lower(name) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_character_catalog_name_kanji_trgm ON character_catalog_entry USING GIN (lower(name_kanji) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_character_catalog_nicknames_trgm ON character_catalog_entry USING GIN (lower(nicknames) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_character_catalog_source_title_trgm ON character_catalog_entry USING GIN (lower(source_anime_title) gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_anime_character_anime_mal_id ON anime_character_appearance (anime_mal_id);
CREATE INDEX IF NOT EXISTS idx_anime_character_character_mal_id ON anime_character_appearance (character_mal_id);
