ALTER TABLE IF EXISTS compte ALTER COLUMN password TYPE VARCHAR(255);
ALTER TABLE IF EXISTS anime_library_entry ADD COLUMN IF NOT EXISTS media_type VARCHAR(40);
ALTER TABLE IF EXISTS manga_library_entry ADD COLUMN IF NOT EXISTS read_volumes INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS manga_library_entry ADD COLUMN IF NOT EXISTS total_volumes INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS manga_library_entry ADD COLUMN IF NOT EXISTS catalog_type VARCHAR(80);
ALTER TABLE IF EXISTS manga_library_entry ADD COLUMN IF NOT EXISTS catalog_score DOUBLE PRECISION;
ALTER TABLE IF EXISTS manga_library_entry ADD COLUMN IF NOT EXISTS catalog_year INTEGER;
ALTER TABLE IF EXISTS manga_library_entry ADD COLUMN IF NOT EXISTS catalog_genres VARCHAR(1200);
ALTER TABLE IF EXISTS manga_library_entry ADD COLUMN IF NOT EXISTS catalog_authors VARCHAR(1200);
UPDATE manga_library_entry SET read_volumes = 0 WHERE read_volumes IS NULL;
UPDATE manga_library_entry SET total_volumes = 0 WHERE total_volumes IS NULL;
ALTER TABLE IF EXISTS account_message ADD COLUMN IF NOT EXISTS image_data BYTEA;
ALTER TABLE IF EXISTS account_message ADD COLUMN IF NOT EXISTS image_content_type VARCHAR(80);
ALTER TABLE IF EXISTS compte ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE IF NOT EXISTS account_session (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL,
    token_hash VARCHAR(96) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_account_session_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_account_session_account FOREIGN KEY (account_id) REFERENCES compte(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_account_session_account ON account_session(account_id);
CREATE INDEX IF NOT EXISTS idx_account_session_expires_at ON account_session(expires_at);

CREATE TABLE IF NOT EXISTS feed_activity_like (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL,
    activity_owner_id INTEGER NOT NULL,
    activity_type VARCHAR(20) NOT NULL,
    activity_entry_id INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_feed_activity_like_account_activity UNIQUE (account_id, activity_type, activity_entry_id),
    CONSTRAINT fk_feed_activity_like_account FOREIGN KEY (account_id) REFERENCES compte(id) ON DELETE CASCADE,
    CONSTRAINT fk_feed_activity_like_owner FOREIGN KEY (activity_owner_id) REFERENCES compte(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_feed_activity_like_activity ON feed_activity_like(activity_type, activity_entry_id);
CREATE INDEX IF NOT EXISTS idx_feed_activity_like_account ON feed_activity_like(account_id);
CREATE INDEX IF NOT EXISTS idx_feed_activity_like_owner ON feed_activity_like(activity_owner_id);

CREATE TABLE IF NOT EXISTS account_message (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id INTEGER NOT NULL,
    recipient_id INTEGER NOT NULL,
    content VARCHAR(1000) NOT NULL,
    image_data BYTEA,
    image_content_type VARCHAR(80),
    read_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_account_message_sender FOREIGN KEY (sender_id) REFERENCES compte(id),
    CONSTRAINT fk_account_message_recipient FOREIGN KEY (recipient_id) REFERENCES compte(id)
);

CREATE INDEX IF NOT EXISTS idx_account_message_pair ON account_message(sender_id, recipient_id, created_at);
CREATE INDEX IF NOT EXISTS idx_account_message_unread ON account_message(recipient_id, sender_id, read_at);

CREATE TABLE IF NOT EXISTS anime_catalog_entry (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mal_id INTEGER NOT NULL,
    slug VARCHAR(140) NOT NULL,
    title VARCHAR(260) NOT NULL,
    title_english VARCHAR(260),
    title_japanese VARCHAR(260),
    image_url VARCHAR(700),
    background_url VARCHAR(700),
    synopsis VARCHAR(5000),
    type VARCHAR(40),
    episodes INTEGER,
    status VARCHAR(80),
    score DOUBLE PRECISION,
    anime_rank INTEGER,
    popularity INTEGER,
    season VARCHAR(32),
    anime_year INTEGER,
    genres VARCHAR(1200),
    studios VARCHAR(1200),
    trailer_url VARCHAR(700),
    last_synced_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_anime_catalog_mal_id UNIQUE (mal_id)
);

CREATE INDEX IF NOT EXISTS idx_anime_catalog_title ON anime_catalog_entry(title);
CREATE INDEX IF NOT EXISTS idx_anime_catalog_popularity ON anime_catalog_entry(popularity);
ALTER TABLE IF EXISTS anime_catalog_entry ADD COLUMN IF NOT EXISTS characters_synced_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE IF NOT EXISTS anime_weekly_ranking (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anime_mal_id INTEGER NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    rank_position INTEGER NOT NULL,
    weekly_score DOUBLE PRECISION NOT NULL,
    source VARCHAR(80) NOT NULL,
    captured_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_anime_weekly_ranking_period_source_anime UNIQUE (source, period_start, period_end, anime_mal_id),
    CONSTRAINT fk_anime_weekly_ranking_anime FOREIGN KEY (anime_mal_id) REFERENCES anime_catalog_entry(mal_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_anime_weekly_ranking_latest ON anime_weekly_ranking(period_end, rank_position);
CREATE INDEX IF NOT EXISTS idx_anime_weekly_ranking_anime ON anime_weekly_ranking(anime_mal_id);

CREATE INDEX IF NOT EXISTS idx_character_source_anime_mal_id ON character_catalog_entry(source_anime_mal_id);

CREATE TABLE IF NOT EXISTS anime_character_appearance (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anime_mal_id INTEGER NOT NULL,
    anime_slug VARCHAR(140),
    anime_title VARCHAR(260),
    anime_image_url VARCHAR(700),
    character_mal_id INTEGER NOT NULL,
    role VARCHAR(40),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_anime_character_appearance UNIQUE (anime_mal_id, character_mal_id)
);

CREATE INDEX IF NOT EXISTS idx_anime_character_anime_mal_id ON anime_character_appearance(anime_mal_id);
CREATE INDEX IF NOT EXISTS idx_anime_character_character_mal_id ON anime_character_appearance(character_mal_id);
