CREATE EXTENSION IF NOT EXISTS pg_trgm;

ALTER TABLE IF EXISTS compte ADD COLUMN IF NOT EXISTS legacy_pseudo VARCHAR(80);
ALTER TABLE IF EXISTS compte ADD COLUMN IF NOT EXISTS username_change_required BOOLEAN;
ALTER TABLE IF EXISTS compte ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE IF EXISTS compte ADD COLUMN IF NOT EXISTS show_online_discovery BOOLEAN DEFAULT false;
ALTER TABLE IF EXISTS compte ALTER COLUMN password TYPE VARCHAR(255);

CREATE TABLE IF NOT EXISTS account_session (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL,
    token_hash VARCHAR(96) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_account_session_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_account_session_account FOREIGN KEY (account_id) REFERENCES compte(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS feed_activity_like (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INTEGER NOT NULL,
    activity_owner_id INTEGER NOT NULL,
    activity_type VARCHAR(20) NOT NULL,
    activity_entry_id INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_feed_activity_like_account_activity UNIQUE (account_id, activity_type, activity_entry_id),
    CONSTRAINT fk_feed_activity_like_account FOREIGN KEY (account_id) REFERENCES compte(id) ON DELETE CASCADE,
    CONSTRAINT fk_feed_activity_like_owner FOREIGN KEY (activity_owner_id) REFERENCES compte(id) ON DELETE CASCADE
);

ALTER TABLE IF EXISTS anime_library_entry ADD COLUMN IF NOT EXISTS media_type VARCHAR(40);
ALTER TABLE IF EXISTS manga_library_entry ADD COLUMN IF NOT EXISTS read_volumes INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS manga_library_entry ADD COLUMN IF NOT EXISTS total_volumes INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS manga_library_entry ADD COLUMN IF NOT EXISTS catalog_type VARCHAR(80);
ALTER TABLE IF EXISTS manga_library_entry ADD COLUMN IF NOT EXISTS catalog_score DOUBLE PRECISION;
ALTER TABLE IF EXISTS manga_library_entry ADD COLUMN IF NOT EXISTS catalog_year INTEGER;
ALTER TABLE IF EXISTS manga_library_entry ADD COLUMN IF NOT EXISTS catalog_genres VARCHAR(1200);
ALTER TABLE IF EXISTS manga_library_entry ADD COLUMN IF NOT EXISTS catalog_authors VARCHAR(1200);
UPDATE manga_library_entry SET read_volumes = 0 WHERE read_volumes IS NULL;
UPDATE manga_library_entry SET total_volumes = 0 WHERE total_volumes IS NULL;
ALTER TABLE IF EXISTS account_message ADD COLUMN IF NOT EXISTS image_data BYTEA;
ALTER TABLE IF EXISTS account_message ADD COLUMN IF NOT EXISTS image_content_type VARCHAR(80);
ALTER TABLE IF EXISTS anime_catalog_entry ADD COLUMN IF NOT EXISTS characters_synced_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE IF NOT EXISTS anime_weekly_ranking (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anime_mal_id INTEGER NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    rank_position INTEGER NOT NULL,
    weekly_score DOUBLE PRECISION NOT NULL,
    source VARCHAR(80) NOT NULL,
    captured_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_anime_weekly_ranking_period_source_anime UNIQUE (source, period_start, period_end, anime_mal_id),
    CONSTRAINT fk_anime_weekly_ranking_anime FOREIGN KEY (anime_mal_id) REFERENCES anime_catalog_entry(mal_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_compte_lower_pseudo ON compte (lower(pseudo));
CREATE INDEX IF NOT EXISTS idx_compte_lower_mail ON compte (lower(mail));
CREATE INDEX IF NOT EXISTS idx_compte_lower_legacy_pseudo ON compte (lower(legacy_pseudo));
CREATE INDEX IF NOT EXISTS idx_compte_email_confirmation_token ON compte (email_confirmation_token);
CREATE INDEX IF NOT EXISTS idx_compte_password_reset_token ON compte (password_reset_token);
CREATE INDEX IF NOT EXISTS idx_compte_online_discovery ON compte (show_online_discovery, last_active_at DESC);
CREATE INDEX IF NOT EXISTS idx_account_session_account ON account_session (account_id);
CREATE INDEX IF NOT EXISTS idx_account_session_expires_at ON account_session (expires_at);
CREATE INDEX IF NOT EXISTS idx_feed_activity_like_activity ON feed_activity_like (activity_type, activity_entry_id);
CREATE INDEX IF NOT EXISTS idx_feed_activity_like_account ON feed_activity_like (account_id);
CREATE INDEX IF NOT EXISTS idx_feed_activity_like_owner ON feed_activity_like (activity_owner_id);

CREATE INDEX IF NOT EXISTS idx_account_follow_followed_created ON account_follow (followed_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_account_follow_follower_created ON account_follow (follower_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_account_notification_recipient_created ON account_notification (recipient_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_account_notification_recipient_unread ON account_notification (recipient_id, read_at);
CREATE INDEX IF NOT EXISTS idx_account_notification_recipient_type_unread ON account_notification (recipient_id, type, read_at);

CREATE INDEX IF NOT EXISTS idx_account_message_pair ON account_message (sender_id, recipient_id, created_at);
CREATE INDEX IF NOT EXISTS idx_account_message_reverse_pair ON account_message (recipient_id, sender_id, created_at);
CREATE INDEX IF NOT EXISTS idx_account_message_unread ON account_message (recipient_id, sender_id, read_at);

CREATE INDEX IF NOT EXISTS idx_anime_library_account_updated ON anime_library_entry (account_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_manga_library_account_updated ON manga_library_entry (account_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_anime_catalog_title ON anime_catalog_entry (title);
CREATE INDEX IF NOT EXISTS idx_anime_catalog_popularity ON anime_catalog_entry (popularity);
CREATE INDEX IF NOT EXISTS idx_anime_catalog_filters ON anime_catalog_entry (status, anime_year, season, score, type);
CREATE INDEX IF NOT EXISTS idx_anime_catalog_pending_character_sync
    ON anime_catalog_entry (popularity, title, mal_id)
    WHERE mal_id IS NOT NULL AND characters_synced_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_anime_weekly_ranking_latest ON anime_weekly_ranking (period_end, rank_position);
CREATE INDEX IF NOT EXISTS idx_anime_weekly_ranking_anime ON anime_weekly_ranking (anime_mal_id);
CREATE INDEX IF NOT EXISTS idx_anime_catalog_title_trgm ON anime_catalog_entry USING GIN (lower(title) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_anime_catalog_title_english_trgm ON anime_catalog_entry USING GIN (lower(title_english) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_anime_catalog_title_japanese_trgm ON anime_catalog_entry USING GIN (lower(title_japanese) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_anime_catalog_genres_trgm ON anime_catalog_entry USING GIN (lower(genres) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_anime_catalog_studios_trgm ON anime_catalog_entry USING GIN (lower(studios) gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_character_source_anime_mal_id ON character_catalog_entry (source_anime_mal_id);
CREATE INDEX IF NOT EXISTS idx_character_catalog_name ON character_catalog_entry (name);
CREATE INDEX IF NOT EXISTS idx_character_catalog_favorites ON character_catalog_entry (favorites DESC);
CREATE INDEX IF NOT EXISTS idx_character_catalog_name_trgm ON character_catalog_entry USING GIN (lower(name) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_character_catalog_name_kanji_trgm ON character_catalog_entry USING GIN (lower(name_kanji) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_character_catalog_nicknames_trgm ON character_catalog_entry USING GIN (lower(nicknames) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_character_catalog_source_title_trgm ON character_catalog_entry USING GIN (lower(source_anime_title) gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_anime_character_anime_mal_id ON anime_character_appearance (anime_mal_id);
CREATE INDEX IF NOT EXISTS idx_anime_character_character_mal_id ON anime_character_appearance (character_mal_id);
